import Analytics from './Analytics';
import { LANGUAGES, t } from './i18n';
import { useState } from 'react';
import { AlertCircle, ArrowDownLeft, ArrowRight, ArrowUpRight, Check, ChevronRight, Clock3, Cpu, FileClock, Gauge, HardDrive, Info, Keyboard, LoaderCircle, MemoryStick, Monitor, Moon, Pause, Play, Power, RefreshCw, Search, ShieldCheck, Sun, Trash2, Zap } from 'lucide-react';
import { isDesktop } from './api';
import type { Page } from './navigation';
import Processes from './Processes';
import SensorPanel from './SensorPanel';
import { SENSORS, summarize } from './usePulse';
import type { PulseModel, Sensor } from './usePulse';
import { Badge, ChartLegend, DataRow, EmptyState, HistoryChart, Meter, MetricTile, PageHeader, RowLink, SectionHeader, Segmented, Toggle, dateText, formatBytes, formatNumber, metricText, timeText } from './ui';

const PROFILE_COPY: Record<string, string> = { balanced: 'Untuk penggunaan sehari hari.', gaming: 'Prioritaskan performa saat dibutuhkan.', saving: 'Kurangi konsumsi daya perangkat.' };
const CAP_NAMES: Record<string, string> = { cpu_usage: 'Penggunaan CPU', ram_usage: 'Penggunaan memori', disk_capacity: 'Kapasitas penyimpanan', network_rate: 'Aktivitas jaringan', cpu_temperature: 'Suhu CPU', gpu_usage: 'Penggunaan GPU', gpu_temperature: 'Suhu GPU', gpu_adapters: 'Adapter grafis', power_plans: 'Profil daya Windows', user_temp_cleaner: 'Pembersihan file sementara' };
type Props = { page: Page; model: PulseModel; sensor: Sensor; setSensor: (value: Sensor) => void; navigate: (page: Page) => void };

export default function Views({ page, model: m, sensor, setSensor, navigate }: Props) {
  const [capFilter, setCapFilter] = useState<'all' | 'unavailable'>('all');
  const { snapshot: s, info, settings, samples, running, busy, activePlan, activeSession, selectedMapping } = m;
  const points = (key: Sensor) => samples.map(sample => sample[key]);
  const chartPlots = SENSORS.map(item => ({ key: item.value, label: t(item.label), values: points(item.value) }));
  const legend = SENSORS.map(item => ({ key: item.value, label: item.label }));
  const pauseButton = <button className="button" onClick={() => m.setRunning(!running)}>{running ? <Pause size={14} /> : <Play size={14} />}{running ? t("Jeda monitoring") : t("Lanjutkan")}</button>;
  const openSensor = (value: Sensor) => { setSensor(value); navigate('monitor'); };

  if (page === 'dashboard') return <>
    <PageHeader title={t("Ringkasan")} description={t("Satu pandangan untuk kondisi perangkat Anda.")} actions={pauseButton} />
    <section className="device-overview"><div className="device-overview-title"><Monitor size={24} strokeWidth={1.4} /><div><strong>{info?.device_name ?? t("Menghubungkan perangkat")}</strong><span>{info?.operating_system ?? 'Windows'}<b>·</b>{info ? t("{0} logical core", { 0: info.cpu_cores }) : t("Mendeteksi hardware")}</span></div></div><button className="quiet-button" onClick={() => navigate('system')}>{t("Detail perangkat")}<ArrowUpRight size={14} /></button></section>
    <div className="metric-strip">
      <MetricTile title="CPU" metric={s?.cpu_usage} detail={s?.cpu_name ?? t("Mendeteksi prosesor")} icon={Cpu} values={points('cpu')} plot="cpu" onClick={() => openSensor('cpu')} />
      <MetricTile title="GPU" metric={s?.gpu_usage} detail={s?.gpu_name ?? t("Mendeteksi grafis")} icon={Gauge} values={points('gpu')} plot="gpu" onClick={() => openSensor('gpu')} />
      <MetricTile title={t("Memori")} metric={s?.ram_usage} detail={`${metricText(s?.ram_used_gb)} / ${metricText(s?.ram_total_gb)}`} icon={MemoryStick} values={points('ram')} plot="ram" onClick={() => openSensor('ram')} />
      <MetricTile title={t("Penyimpanan")} metric={s && m.diskPercent != null ? { ...s.disk_used_gb, value: m.diskPercent, unit: '%' } : undefined} detail={m.freeDisk != null ? t("{0} GB tersedia", { 0: formatNumber(m.freeDisk, 1) }) : t("Mendeteksi kapasitas")} icon={HardDrive} values={samples.map(() => m.diskPercent)} plot="disk" onClick={() => navigate('system')} />
    </div>
    <div className="dashboard-grid"><section className="surface chart-surface"><SectionHeader title={t("Aktivitas sumber daya")} action={<button className="quiet-button" onClick={() => navigate('monitor')}>{t("Buka monitor")}<ArrowUpRight size={14} /></button>} /><ChartLegend items={legend} /><HistoryChart plots={chartPlots} times={samples.map(sample => sample.time)} /></section><section className="surface power-summary"><SectionHeader title={t("Profil daya")} action={<Power size={16} className="muted" />} /><div className="power-summary-current"><span>{t("Skema Windows aktif")}</span><strong>{activePlan?.name ?? t("Belum terdeteksi")}</strong><Badge status={activeSession?.status ?? 'supported'}>{activeSession ? activeSession.status === 'active' ? t("Sesi tuning aktif") : t("Perlu ditinjau") : t("Tanpa sesi tuning")}</Badge></div><DataRow label={t("Sumber daya")} value={s?.power_source ?? info?.power_source ?? '—'} /><button className="button button-wide" onClick={() => navigate('tuner')}>{t("Kelola profil")}<ArrowRight size={14} /></button></section></div>
    <section className="surface vitals-surface"><SectionHeader title={t("Pembacaan tambahan")} description={t("Suhu dan jaringan saat ini")} /><div className="vitals-grid"><DataRow icon={Cpu} label={t("Suhu CPU")} value={metricText(s?.cpu_temperature)} /><DataRow icon={Gauge} label={t("Suhu GPU")} value={metricText(s?.gpu_temperature)} /><DataRow icon={ArrowDownLeft} label={t("Unduh")} value={metricText(s?.network_down_kbps)} /><DataRow icon={ArrowUpRight} label={t("Unggah")} value={metricText(s?.network_up_kbps)} /></div></section>
  </>;

  if (page === 'monitor') {
    const metric = sensor === 'cpu' ? s?.cpu_usage : sensor === 'gpu' ? s?.gpu_usage : s?.ram_usage;
    const name = sensor === 'cpu' ? s?.cpu_name : sensor === 'gpu' ? s?.gpu_name : t("Memori sistem");
    const stats = summarize(points(sensor));
    return <><PageHeader title={t("Monitor")} description={t("Pembacaan hardware langsung, dengan sumber data yang jelas.")} actions={pauseButton} />
      <div className="monitor-tabs" role="tablist" aria-label={t("Sumber daya")}>{SENSORS.map(item => <button role="tab" aria-selected={sensor === item.value} aria-controls="sensor-detail" key={item.value} className={sensor === item.value ? 'is-selected' : ''} onClick={() => setSensor(item.value)}>{t(item.label)}<span>{metricText(item.value === 'cpu' ? s?.cpu_usage : item.value === 'gpu' ? s?.gpu_usage : s?.ram_usage, 0)}</span></button>)}</div>
      {sensor === 'gpu' && <SensorPanel model={m} />}
      <section className="surface sensor-detail" id="sensor-detail" role="tabpanel" aria-label={t("Detail {0}", { 0: sensor })}><div className="sensor-heading"><div><span className="overline">{SENSORS.find(item => item.value === sensor)?.label}</span><h2>{name ?? t("Mendeteksi perangkat")}</h2><p>{metric?.source ?? t("Menunggu sumber data")}</p></div><div className="sensor-reading"><strong>{formatNumber(metric?.value, 1)}<span>{metric?.value != null ? '%' : ''}</span></strong><Badge status={metric?.status ?? 'unknown'} /></div></div><HistoryChart plots={[{ key: sensor, label: SENSORS.find(item => item.value === sensor)!.label, values: points(sensor) }]} times={samples.map(sample => sample.time)} tall /><div className="sensor-stats"><span>{t("Rata rata")}<strong>{formatNumber(stats.average, 1)}{stats.count ? '%' : ''}</strong></span><span>{t("Terendah")}<strong>{formatNumber(stats.min, 1)}{stats.count ? '%' : ''}</strong></span><span>{t("Tertinggi")}<strong>{formatNumber(stats.max, 1)}{stats.count ? '%' : ''}</strong></span><span>{t("Sampel valid")}<strong>{stats.count}</strong></span></div></section>
      <div className="two-column"><section className="surface"><SectionHeader title={t("Komputasi")} /><DataRow label={t("Penggunaan CPU")} value={metricText(s?.cpu_usage)} detail={s?.cpu_usage.source} /><DataRow label={t("Suhu CPU")} value={metricText(s?.cpu_temperature)} detail={s?.cpu_temperature.source} /><DataRow label={t("Penggunaan GPU")} value={metricText(s?.gpu_usage)} detail={s?.gpu_usage.source} /><DataRow label={t("Suhu GPU")} value={metricText(s?.gpu_temperature)} detail={s?.gpu_temperature.source} /></section><section className="surface"><SectionHeader title={t("Kapasitas & jaringan")} /><DataRow label={t("Memori terpakai")} value={metricText(s?.ram_used_gb)} detail={t("Total {0}", { 0: metricText(s?.ram_total_gb) })} /><DataRow label={t("Penyimpanan")} value={metricText(s?.disk_used_gb)} detail={t("{0} · total {1}", { 0: s?.disk_name || 'Volume sistem', 1: metricText(s?.disk_total_gb) })} /><DataRow label={t("Unduh")} value={metricText(s?.network_down_kbps)} /><DataRow label={t("Unggah")} value={metricText(s?.network_up_kbps)} /></section></div>
      <div className="inline-note"><Info size={15} /><span>{t("Sensor yang tidak didukung ditampilkan sebagai tidak tersedia. Angka nol hanya berarti penggunaan yang terukur.")}</span></div>
    </>;
  }

  if (page === 'analytics') return <Analytics model={m} />;
  if (page === 'processes') return <Processes />;

  if (page === 'tuner') return <>
    <PageHeader title={t("Profil daya")} description={t("Atur penggunaan daya melalui skema Windows yang tersedia.")} />
    <div className="current-plan-strip"><Power size={19} /><div><span>{t("Skema aktif")}</span><strong>{activePlan?.name ?? t("Belum terdeteksi")}</strong></div><span className="current-plan-source">{s?.power_source ?? info?.power_source ?? '—'}</span></div>
    {activeSession && <div className="notice"><AlertCircle size={18} /><div><strong>{activeSession.status === 'active' ? t("Sesi tuning sedang aktif") : t("Sesi tuning perlu ditinjau")}</strong><p>{t("Skema sebelumnya:")}{' '}{m.plans.find(plan => plan.guid === activeSession.previous_guid)?.name ?? activeSession.previous_guid}.{activeSession.error && ` ${t(activeSession.error)}`}</p></div><button className="button" disabled={Boolean(busy)} onClick={() => activeSession.status === 'conflict' ? m.setConfirmation('restore') : void m.restore()}>{busy === 'restore' ? <LoaderCircle size={14} className="spin" /> : <RefreshCw size={14} />}{t("Pulihkan")}</button></div>}
    <div className="profile-workbench"><section className="profile-list"><h2>{t("Profil Anda")}</h2>{m.profiles.length ? m.profiles.map(profile => <button key={profile.id} className={`profile-choice ${m.selectedProfile === profile.id ? 'is-selected' : ''}`} aria-pressed={m.selectedProfile === profile.id} disabled={Boolean(busy)} onClick={() => m.setSelectedProfile(profile.id)}><span className="profile-choice-icon">{profile.id === 'gaming' ? <Zap size={19} /> : profile.id === 'saving' ? <Power size={19} /> : <Gauge size={19} />}</span><span><strong>{t(profile.name)}</strong><small>{t(PROFILE_COPY[profile.id] ?? 'Profil perangkat')}</small></span><ChevronRight size={15} /></button>) : <EmptyState icon={Gauge} title={t("Profil belum tersedia")} description={t("Muat ulang informasi perangkat untuk membaca profil.")} />}<p className="profile-list-note">{t("Setiap profil dipetakan ke satu skema daya yang tersedia di PC ini.")}</p></section><section className="surface profile-editor"><SectionHeader title={selectedMapping ? t(selectedMapping.name) : t("Pilih profil")} description={t("Pemetaan & aktivasi")} /><label className="field-label" htmlFor="power-scheme">{t("Skema daya Windows")}</label><select id="power-scheme" disabled={!selectedMapping || Boolean(busy) || Boolean(activeSession && activeSession.profile_id === selectedMapping.id)} value={selectedMapping?.scheme_guid ?? ''} onChange={event => void m.mapProfile(event.target.value, selectedMapping?.ac_only ?? false)}><option value="">{t("Pilih skema daya…")}</option>{m.plans.map(plan => <option key={plan.guid} value={plan.guid}>{plan.name}{plan.active ? t(" (aktif)") : ''}</option>)}</select><p className="field-help">{activeSession && activeSession.profile_id === selectedMapping?.id ? t("Pulihkan profil ini sebelum mengubah pengaturannya.") : t("Hanya skema yang ditemukan di Windows dapat digunakan.")}</p><div className="setting-row"><div><strong>{t("Hanya saat terhubung ke listrik")}</strong><p>{t("Profil dipulihkan saat perangkat beralih ke baterai.")}</p></div><Toggle label={t("Hanya saat daya AC")} checked={selectedMapping?.ac_only ?? false} disabled={!selectedMapping || Boolean(busy) || Boolean(activeSession && activeSession.profile_id === selectedMapping.id)} onChange={checked => void m.mapProfile(selectedMapping?.scheme_guid ?? '', checked)} /></div><div className="profile-editor-footer"><button className="button button-primary" disabled={!isDesktop || !selectedMapping?.scheme_guid || Boolean(activeSession) || Boolean(busy)} onClick={() => void m.activate()}>{busy === 'tuning' ? <LoaderCircle size={15} className="spin" /> : <Zap size={15} />}{t("Terapkan profil")}</button><p>{activeSession ? t("Pulihkan sesi saat ini sebelum menerapkan profil lain.") : !selectedMapping?.scheme_guid ? t("Pilih skema untuk mengaktifkan profil ini.") : t("Skema sebelumnya disimpan agar dapat dipulihkan.")}</p></div></section></div>
    <section className="surface table-surface"><SectionHeader title={t("Skema yang tersedia")} action={<button className="quiet-button" disabled={Boolean(busy)} onClick={() => void m.refreshContext()}><RefreshCw size={13} />{t("Muat ulang")}</button>} /><div className="scheme-list">{m.plans.length ? m.plans.map(plan => <div className="scheme-row" key={plan.guid}><Power size={16} className="muted" /><div><strong>{plan.name}</strong><small>{plan.guid}</small></div>{plan.active && <Badge status="active" />}</div>) : <EmptyState icon={Power} title={t("Skema belum ditemukan")} description={t("Deteksi ulang perangkat untuk memeriksa skema Windows.")} />}</div></section>
  </>;

  if (page === 'cleaner') return <>
    <PageHeader title={t("Pembersihan")} description={t("Tinjau file sementara sebelum mengosongkan ruang.")} />
    {(busy === 'clean' || m.cleanupProgress) && <section className="cleanup-progress surface" aria-label={t("Progres pembersihan")}>
      <div className="cleanup-progress-heading">{busy === 'clean' ? <LoaderCircle size={16} className="spin" /> : <Check size={16} />}<strong>{busy === 'clean' ? m.cancelRequested ? t("Menunggu pembatalan…") : t("Membersihkan…") : t("Hasil pembersihan terakhir")}</strong>{busy !== 'clean' && m.cleanupProgress && <Badge status={m.cleanupProgress.status} />}<span>{t("{0} dari {1} file diperiksa", { 0: formatNumber(m.cleanupProgress?.processed_count ?? 0), 1: formatNumber(m.cleanupProgress?.total_count ?? m.scan?.eligible_count ?? 0) })}</span></div>
      <progress aria-label={t("Progres pembersihan")} max={Math.max(1, m.cleanupProgress?.total_count ?? m.scan?.eligible_count ?? 1)} value={m.cleanupProgress?.processed_count ?? 0} />
      <div className="cleanup-progress-counts"><span>{t("{0} dibersihkan", { 0: formatBytes(m.cleanupProgress?.recovered_bytes ?? 0) })}</span><span>{t("{0} dilewati · {1} gagal", { 0: formatNumber(m.cleanupProgress?.skipped_count ?? 0), 1: formatNumber(m.cleanupProgress?.error_count ?? 0) })}</span></div>
    </section>}
    <div className="cleaner-steps" aria-label={t("Tahapan pembersihan")}>{[t("Pindai file"), t("Tinjau hasil"), t("Konfirmasi")].map((label, index) => <span key={label} className={(m.scan ? index <= 1 : index === 0) ? 'is-active' : ''}><b>{index + 1}</b>{label}{index < 2 && <ChevronRight size={14} />}</span>)}</div>
    <div className="cleaner-workbench"><section className="cleaner-scope"><span className="scope-symbol"><FileClock size={29} strokeWidth={1.3} /></span><h2>{t("File sementara pengguna")}</h2><p>{t("Temukan file lama di folder temp akun Anda. Pemindaian tidak menghapus file.")}</p><div className="scope-rules"><div><Clock3 size={16} /><span>{t("Lebih lama dari 24 jam")}</span></div><div><ShieldCheck size={16} /><span>{t("File aktif dan tidak aman dilewati")}</span></div><div><HardDrive size={16} /><span>{t("Dokumen pribadi tidak termasuk")}</span></div></div><button className="button button-primary" disabled={Boolean(busy)} onClick={() => void m.startScan()}>{busy === 'scan' ? <LoaderCircle size={15} className="spin" /> : <Search size={15} />}{busy === 'scan' ? t("Memindai file…") : m.scan ? t("Pindai ulang") : t("Pindai sekarang")}</button></section><section className="scan-result"><SectionHeader title={t("Hasil pemindaian")} />{busy === 'scan' ? <div className="scan-loading"><LoaderCircle size={27} className="spin" /><strong>{t("Memeriksa file sementara")}</strong><p>{t("Ukuran dan kondisi file sedang dibaca.")}</p></div> : m.scan ? <><span className="scan-label">{t("Perkiraan ruang yang dapat dibersihkan")}</span><div className="scan-size">{formatBytes(m.scan.estimated_bytes)}</div><div className="scan-counters"><span><strong>{formatNumber(m.scan.eligible_count)}</strong>{t("File memenuhi syarat")}</span><span><strong>{formatNumber(m.scan.skipped_count)}</strong>{t("File dilewati")}</span></div><p className={`scan-expiry ${m.expiredScan ? 'emphasis' : ''}`}><Clock3 size={13} />{m.expiredScan ? t("Hasil kedaluwarsa. Pindai ulang untuk melanjutkan.") : t("Berlaku sampai {0}", { 0: timeText(m.scan.expires_at) })}</p>{m.scan.warnings.map((warning, index) => <p className="scan-warning" key={index}><Info size={14} />{t(warning)}</p>)}<button className="button button-primary button-wide" disabled={!m.canClean} onClick={() => m.setConfirmation('clean')}>{busy === 'clean' ? <LoaderCircle size={15} className="spin" /> : <Trash2 size={15} />}{busy === 'clean' ? t("Membersihkan…") : t("Tinjau & bersihkan")}</button>{busy === 'clean' && <button className="quiet-button cancel-clean" disabled={m.cancelRequested} onClick={() => void m.cancelClean()}>{t("Batalkan sisa pembersihan")}</button>}</> : <EmptyState icon={Search} title={t("Siap untuk dipindai")} description={t("Hasil dan estimasi ruang akan muncul di sini. Anda memutuskan kapan file dihapus.")} />}</section></div>
    <section className="surface table-surface"><SectionHeader title={t("Riwayat pembersihan")} description={t("Hasil berdasarkan file yang berhasil dihapus.")} />{m.cleanHistory.length ? <div className="table-scroll"><table><thead><tr><th>{t("Waktu")}</th><th>{t("Dibersihkan")}</th><th>{t("Dihapus / dilewati / gagal")}</th><th>{t("Status")}</th></tr></thead><tbody>{m.cleanHistory.map(item => <tr key={item.id}><td>{dateText(item.finished_at)}</td><td>{formatBytes(item.recovered_bytes)}</td><td>{item.deleted_count} / {item.skipped_count} / {item.error_count}</td><td><Badge status={item.status} /></td></tr>)}</tbody></table></div> : <EmptyState icon={FileClock} title={t("Belum ada pembersihan")} description={t("Riwayat akan tampil setelah Anda menjalankan pembersihan pertama.")} />}</section>
  </>;

  if (page === 'system') {
    const unavailable = m.capabilities.filter(capability => capability.status !== 'supported');
    const capabilities = capFilter === 'all' ? m.capabilities : unavailable;
    return <><PageHeader title={t("Perangkat")} description={t("Identitas hardware dan kemampuan yang terdeteksi.")} actions={<button className="button" disabled={Boolean(busy)} onClick={() => void m.refreshDetection()}><RefreshCw size={14} className={busy === 'detect' ? 'spin' : ''} />{t("Deteksi ulang")}</button>} />
      <section className="device-identity"><Monitor size={39} strokeWidth={1.1} /><div><h2>{info?.device_name ?? t("Menghubungkan perangkat")}</h2><p>{info?.operating_system ?? 'Windows'}</p></div><span className="identity-tag">{t("PERANGKAT INI")}</span></section>
      <div className="two-column"><section className="surface"><SectionHeader title={t("Hardware utama")} /><DataRow icon={Cpu} label={t("Prosesor")} value={info?.cpu_model ?? '—'} /><DataRow label={t("Logical core")} value={info?.cpu_cores ?? '—'} /><DataRow icon={MemoryStick} label={t("Memori terpasang")} value={info ? formatBytes(info.ram_total_bytes) : '—'} /><DataRow icon={Power} label={t("Sumber daya")} value={info?.power_source ?? '—'} /></section><section className="surface"><SectionHeader title={t("Grafis & penyimpanan")} />{info?.gpu_adapters.length ? info.gpu_adapters.map((gpu, index) => <DataRow key={gpu} icon={Gauge} label={t("Adapter {0}", { 0: index + 1 })} value={gpu} />) : <DataRow icon={Gauge} label={t("Adapter grafis")} value={t("Belum terdeteksi")} />}<DataRow icon={HardDrive} label={s?.disk_name || t("Volume sistem")} value={`${metricText(s?.disk_used_gb)} / ${metricText(s?.disk_total_gb)}`} /><div className="disk-meter"><Meter value={m.diskPercent} label={t("Penggunaan disk")} /><span>{m.freeDisk != null ? t("{0} GB tersedia", { 0: formatNumber(m.freeDisk, 1) }) : t("Kapasitas belum tersedia")}</span></div></section></div>
      <section className="surface capability-surface"><SectionHeader title={t("Kemampuan perangkat")} description={t("Ketersediaan fitur mengikuti sensor dan akses perangkat.")} action={<Segmented<'all' | 'unavailable'> label={t("Filter kemampuan")} value={capFilter} options={[{ value: 'all', label: t("Semua ({0})", { 0: m.capabilities.length }) }, { value: 'unavailable', label: t("Perlu ditinjau ({0})", { 0: unavailable.length }) }]} onChange={setCapFilter} />} />{capabilities.length ? capabilities.map(capability => <div className="capability-row" key={capability.capability_key}><div><strong>{t(CAP_NAMES[capability.capability_key] ?? capability.capability_key.replaceAll('_', ' '))}</strong><p>{t(capability.reason)}</p></div><Badge status={capability.status} /></div>) : <EmptyState icon={ShieldCheck} title={m.capabilities.length ? t("Semua kemampuan tersedia") : t("Menunggu hasil deteksi")} description={m.capabilities.length ? t("Tidak ada kemampuan yang perlu ditinjau.") : t("Informasi kemampuan akan muncul setelah perangkat terdeteksi.")} />}</section>
    </>;
  }

  return <><PageHeader title={t("Pengaturan")} description={t("Sesuaikan tampilan, monitoring, dan penyimpanan data.")} /><div className="settings-layout">
    <section className="settings-section"><div className="settings-section-label"><h2>{t("Tampilan")}</h2><p>{t("Pilih suasana ruang kerja Anda.")}</p></div><div className="settings-section-body"><div className="theme-options" role="group" aria-label={t("Tema aplikasi")}>{([{ value: 'dark', label: t("Gelap"), icon: Moon }, { value: 'light', label: t("Terang"), icon: Sun }, { value: 'system', label: t("Ikuti sistem"), icon: Monitor }] as const).map(theme => <button key={theme.value} className={`theme-choice ${settings.theme === theme.value ? 'is-selected' : ''}`} aria-pressed={settings.theme === theme.value} disabled={Boolean(busy)} onClick={() => void m.saveSettings({ ...settings, theme: theme.value })}><span className={`theme-preview preview-${theme.value}`} aria-hidden="true"><i /><b><em /><em /><em /></b></span><span><theme.icon size={14} />{theme.label}{settings.theme === theme.value && <Check size={13} />}</span></button>)}</div></div></section>
    <section className="settings-section"><div className="settings-section-label"><h2>{t('Bahasa')}</h2><p>{t('Pilih bahasa antarmuka.')}</p></div><div className="settings-section-body"><label className="field-label" htmlFor="app-language">{t('Bahasa aplikasi')}</label><select id="app-language" value={settings.language} disabled={Boolean(busy)} onChange={event => void m.saveSettings({ ...settings, language: event.target.value as typeof settings.language })}>{LANGUAGES.map(language => <option key={language.value} value={language.value}>{language.label}</option>)}</select><p className="field-help">{t('Perubahan langsung diterapkan dan tersimpan di perangkat.')}</p></div></section>
    <section className="settings-section"><div className="settings-section-label"><h2>{t("Monitoring")}</h2><p>{t("Atur kapan dan seberapa sering data dibaca.")}</p></div><div className="settings-section-body"><div className="setting-row"><div><strong>{t("Interval pembaruan")}</strong><p>{t("Jeda antar pembacaan hardware.")}</p></div><Segmented<1 | 2 | 5> label={t("Interval pembaruan")} value={settings.refresh_seconds} options={[{ value: 1, label: t("1 dtk") }, { value: 2, label: t("2 dtk") }, { value: 5, label: t("5 dtk") }]} disabled={Boolean(busy)} onChange={value => void m.saveSettings({ ...settings, refresh_seconds: value })} /></div><div className="setting-row"><div><strong>{t("Monitoring di latar belakang")}</strong><p>{t("Terus ambil data saat jendela diminimalkan.")}</p></div><Toggle label={t("Monitoring di latar belakang")} checked={settings.monitor_in_background} disabled={Boolean(busy)} onChange={checked => void m.saveSettings({ ...settings, monitor_in_background: checked })} /></div></div></section>
    <section className="settings-section"><div className="settings-section-label"><h2>{t("Sensor hardware")}</h2><p>{t("Pilih adapter yang ingin dipantau.")}</p></div><div className="settings-section-body"><SensorPanel model={m} /></div></section>
    <section className="settings-section"><div className="settings-section-label"><h2>{t("Data lokal")}</h2><p>{t("Kendalikan riwayat yang tersimpan.")}</p></div><div className="settings-section-body"><div className="setting-row"><div><strong>{t("Simpan sampel mentah")}</strong><p>{t("Data yang lebih lama diringkas secara berkala.")}</p></div><label className="sr-only" htmlFor="retention">{t("Retensi sampel mentah")}</label><select id="retention" disabled={Boolean(busy)} value={settings.history_retention_hours} onChange={event => void m.saveSettings({ ...settings, history_retention_hours: Number(event.target.value) })}><option value={6}>{t("6 jam")}</option><option value={24}>{t("24 jam")}</option><option value={72}>{t("3 hari")}</option></select></div><div className="setting-row"><div><strong>{t("Hapus riwayat monitoring")}</strong><p>{t("Sampel dan agregat dihapus permanen.")}</p></div><button className="button" disabled={!isDesktop || Boolean(busy)} onClick={() => m.setConfirmation('purge')}><Trash2 size={14} />{t("Hapus riwayat")}</button></div><DataRow label={t("Penyimpanan riwayat")} value={t(({waiting:'Menunggu sampel',healthy:'Tersimpan',degraded:'Terganggu',demo:'Data simulasi'})[m.persistence.status])} /><DataRow label={t("Sampel terakhir tersimpan")} value={m.persistence.last_saved_at ? dateText(m.persistence.last_saved_at) : '?'} /><DataRow label={t("Sampel terlewat sejak aplikasi dibuka")} value={m.persistence.dropped_samples} /><div className="privacy-note"><ShieldCheck size={17} /><p>{t("Data tetap di perangkat Anda. Core Pulse bekerja secara lokal tanpa telemetri atau sinkronisasi cloud.")}</p></div></div></section>
    <section className="settings-section"><div className="settings-section-label"><h2>{t("Navigasi")}</h2><p>{t("Pintasan untuk berpindah lebih cepat.")}</p></div><div className="settings-section-body"><div className="shortcut-row"><span><Search size={15} />{t("Buka halaman atau tindakan")}</span><kbd>Ctrl K</kbd></div><div className="shortcut-row"><span><Keyboard size={15} />{t("Pindah halaman")}</span><kbd>Ctrl 1–8</kbd></div><RowLink title={t("Informasi perangkat")} description={t("Lihat hardware dan ketersediaan fitur.")} icon={Monitor} onClick={() => navigate('system')} /></div></section>
  </div></>;
}
